//
// Created by liran on 13/08/2022.
//

#ifndef ADVANCED_PROGRAMMING_1___EXERCISE_3_CLIENT_H
#define ADVANCED_PROGRAMMING_1___EXERCISE_3_CLIENT_H


class Client {

};


#endif //ADVANCED_PROGRAMMING_1___EXERCISE_3_CLIENT_H
