//
// Created by liran on 25/08/2022.
//

#ifndef ADVANCED_PROGRAMMING_1___EXERCISE_3_STANDARDIO_H
#define ADVANCED_PROGRAMMING_1___EXERCISE_3_STANDARDIO_H


class StandardIO {

};


#endif //ADVANCED_PROGRAMMING_1___EXERCISE_3_STANDARDIO_H
